apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
     app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
      - name: react-vite-app
        image: kiaraahuja/react-vite-app:18
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: react-vite-app
spec:
  type: NodePort
  selector:
    app: react-vite-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000